/* SPDX-License-Identifier: GPL-3.0-only
 * sloopy-sloop-32: the panel files embedded in the firmware (gzip). The table is generated by
 * this component's CMakeLists.txt from the files in web/. */
#pragma once
#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *path;            /* "/index.html" */
    const uint8_t *start, *end;  /* gzip data */
    const char *type;            /* Content-Type */
} web_asset_t;

extern const web_asset_t web_assets[];
extern const size_t web_assets_count;
