/* SPDX-License-Identifier: GPL-3.0-only
 * sloopy-sloop-32: the web panel on the ESP32-S3 (see web_server.h).
 *
 * esp_http_server serves the panel files (gzip, embedded in the firmware: web_assets.c is
 * generated by this component's CMakeLists.txt from web/) and upgrades /ws to a WebSocket.
 * The protocol is components/sloop_proto, as in the host app: the httpd task hands each text
 * message to the hub, a pump task (core 0, ~30 Hz) sends screen changes, LEDs and status. One
 * mutex serialises the hub, so the two tasks never write to the same socket at once.
 */
#include <errno.h>
#include <string.h>
#include <sys/socket.h>

#include "esp_heap_caps.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/task.h"

#include "sloop_proto.h"
#include "web_assets.h"
#include "web_priv.h"
#include "web_server.h"

static const char *TAG = "web";
static httpd_handle_t s_server;
static sloop_proto_hub_t s_hub;
static SemaphoreHandle_t s_mx;
static sloop_web_stats_t s_st;

#define CTX(fd) ((void *)(intptr_t)((fd) + 1))
#define FD(ctx) ((int)(intptr_t)(ctx) - 1)

/* ---------------------------------------------------------------- send --- */
/* httpd's default send makes one send() call and reports a short write as success: a large frame
 * (a screen rectangle) cut short would desynchronise the WebSocket stream. Panel sockets send
 * everything or fail. */
static int send_all(httpd_handle_t hd, int fd, const char *buf, size_t len, int flags)
{
    size_t done = 0;
    (void)hd;
    while (done < len) {
        int r = send(fd, buf + done, len - done, flags);
        if (r < 0 && errno == EINTR)
            continue;
        if (r <= 0)
            return HTTPD_SOCK_ERR_FAIL;
        done += (size_t)r;
    }
    return (int)done;
}

static int ws_send(void *ctx, httpd_ws_type_t type, const uint8_t *p, size_t n)
{
    httpd_ws_frame_t f = {.final = true, .fragmented = false, .type = type, .payload = (uint8_t *)p, .len = n};
    if (httpd_ws_send_frame_async(s_server, FD(ctx), &f) == ESP_OK)
        return 0;
    httpd_sess_trigger_close(s_server, FD(ctx));      /* (a half-sent frame: the panel reconnects) */
    return -1;
}
static int t_text(void *ctx, const char *s, size_t n) { return ws_send(ctx, HTTPD_WS_TYPE_TEXT, (const uint8_t *)s, n); }
static int t_bin(void *ctx, const uint8_t *p, size_t n) { return ws_send(ctx, HTTPD_WS_TYPE_BINARY, p, n); }

/* -------------------------------------------------------------- static --- */
static esp_err_t h_static(httpd_req_t *req)
{
    char path[64];
    size_t i, n = strcspn(req->uri, "?#");
    if (n >= sizeof path)
        n = sizeof path - 1;
    memcpy(path, req->uri, n);
    path[n] = 0;
    if (!strcmp(path, "/"))
        strcpy(path, "/index.html");
    s_st.http_requests++;
    for (i = 0; i < web_assets_count; i++) {
        const web_asset_t *a = &web_assets[i];
        if (!strcmp(path, a->path)) {
            httpd_resp_set_type(req, a->type);
            httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
            httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
            return httpd_resp_send(req, (const char *)a->start, (ssize_t)(a->end - a->start));
        }
    }
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "not found");
    return ESP_OK;
}

/* -------------------------------------------------------------- status --- */
static sloop_web_status_fn s_status_fn;
void sloop_web_set_status_fn(sloop_web_status_fn fn) { s_status_fn = fn; }

static esp_err_t h_status(httpd_req_t *req)
{
    static char buf[1536];
    size_t n = s_status_fn ? s_status_fn(buf, sizeof buf) : 0;
    if (!n)
        n = (size_t)snprintf(buf, sizeof buf, "{}");
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, buf, (ssize_t)n);
}

/* ----------------------------------------------------------- WebSocket --- */
/* (hub locked) the client of this socket, registered on its first frame: ESP-IDF answers the
 * WebSocket handshake itself and calls the handler only for frames */
static int client_of_fd(int fd)
{
    int i;
    for (i = 0; i < SLOOP_PROTO_MAX_CLIENTS; i++)
        if (s_hub.c[i].ctx == CTX(fd))
            return i;
    i = sloop_proto_client_add(&s_hub, CTX(fd));
    s_st.clients = (uint32_t)sloop_proto_clients(&s_hub);
    if (i >= 0)
        httpd_sess_set_send_override(s_server, fd, send_all);
    ESP_LOGI(TAG, "panel connected (fd %d%s), %u panels", fd, i < 0 ? ", refused: too many" : "", (unsigned)s_st.clients);
    return i;
}

static esp_err_t h_ws(httpd_req_t *req)
{
    static char buf[SLOOP_PROTO_TEXT_MAX];
    httpd_ws_frame_t f = {0};
    int fd = httpd_req_to_sockfd(req), ok;
    esp_err_t err;
    if (req->method == HTTP_GET)                       /* (older ESP-IDF: the handshake) */
        return ESP_OK;
    f.type = HTTPD_WS_TYPE_TEXT;
    err = httpd_ws_recv_frame(req, &f, 0);             /* the length first */
    if (err != ESP_OK)
        return err;
    if (f.len >= sizeof buf)
        return ESP_FAIL;                               /* (client messages are small) */
    f.payload = (uint8_t *)buf;
    err = httpd_ws_recv_frame(req, &f, f.len);
    if (err != ESP_OK)
        return err;
    if (f.type != HTTPD_WS_TYPE_TEXT)
        return ESP_OK;
    s_st.ws_messages++;
    xSemaphoreTake(s_mx, portMAX_DELAY);
    ok = client_of_fd(fd) >= 0;
    if (ok)
        sloop_proto_on_text(&s_hub, CTX(fd), buf, f.len);
    xSemaphoreGive(s_mx);
    return ok ? ESP_OK : ESP_FAIL;
}

static void on_close(httpd_handle_t hd, int fd)
{
    int was;
    (void)hd;
    xSemaphoreTake(s_mx, portMAX_DELAY);
    was = sloop_proto_clients(&s_hub);
    sloop_proto_client_remove(&s_hub, CTX(fd));        /* (releases what that panel held) */
    s_st.clients = (uint32_t)sloop_proto_clients(&s_hub);
    xSemaphoreGive(s_mx);
    if ((int)s_st.clients != was)
        ESP_LOGI(TAG, "panel disconnected (fd %d), %u panels", fd, (unsigned)s_st.clients);
    close(fd);
}

static void pump_task(void *arg)
{
    (void)arg;
    for (;;) {
        vTaskDelay(pdMS_TO_TICKS(33));
        xSemaphoreTake(s_mx, portMAX_DELAY);
        sloop_proto_pump(&s_hub);
        s_st.pumps = s_hub.pumps;
        s_st.rects = s_hub.rects;
        xSemaphoreGive(s_mx);
    }
}

esp_err_t sloop_web_start(const char *target, uint16_t port)
{
    httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
    static const sloop_proto_ops_t ops = {t_text, t_bin};
    uint8_t *frame;
    esp_err_t err;
    httpd_uri_t ws = {.uri = "/ws", .method = HTTP_GET, .handler = h_ws, .is_websocket = true};
    httpd_uri_t all = {.uri = "/*", .method = HTTP_GET, .handler = h_static};
    httpd_uri_t status = {.uri = "/api/status", .method = HTTP_GET, .handler = h_status};

    frame = heap_caps_malloc(SLOOP_PROTO_FRAME_BYTES, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!frame)
        frame = heap_caps_malloc(SLOOP_PROTO_FRAME_BYTES, MALLOC_CAP_8BIT);
    s_mx = xSemaphoreCreateMutex();
    if (!frame || !s_mx)
        return ESP_ERR_NO_MEM;
    sloop_proto_hub_init(&s_hub, &ops, target, frame);

    cfg.server_port = port;
    cfg.core_id = 0;                                   /* core 1 belongs to SLOOP */
    cfg.stack_size = 6144;
    cfg.max_open_sockets = 7;
    cfg.max_uri_handlers = 12;
    cfg.lru_purge_enable = true;
    cfg.uri_match_fn = httpd_uri_match_wildcard;
    cfg.close_fn = on_close;
    cfg.send_wait_timeout = 3;
    err = httpd_start(&s_server, &cfg);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "httpd_start: %s", esp_err_to_name(err));
        return err;
    }
    httpd_register_uri_handler(s_server, &ws);
    httpd_register_uri_handler(s_server, &status);
    sloop_settings_register(s_server);
    sloop_ota_register(s_server);
    sloop_store_register(s_server);
    httpd_register_uri_handler(s_server, &all);
    xTaskCreatePinnedToCore(pump_task, "web_pump", 4096, NULL, 4, NULL, 0);
    ESP_LOGI(TAG, "web panel on port %u (%u files embedded)", port, (unsigned)web_assets_count);
    return ESP_OK;
}

void sloop_web_get_stats(sloop_web_stats_t *st) { *st = s_st; }
